### ISSUE TITLE
[Suggestion] Add support for Redstone Arsenal Fishing Rod

### ISSUE THREAD

**Issue by Skillotic0703** [TheIllusiveC4/CombustiveFishing#4]
The Flux-Infused Fishing Rod is an OP fishing rod added by Redstone Arsenal http://teamcofh.com/docs/redstone-arsenal/flux-infused-fishing-rod/ and I think that it would be really cool if it also allowed you to fish in lava.

And also it would be really appreciable if you wrote on the curseforge page what type of integration this mod has with natura! Thank you!

**Comment by TheIllusiveC4** [comment]
You should ask the Redstone Arsenal developers to add this support since they're the ones that implement that particular fishing rod's behavior.

I've updated the CurseForge page with a description of the Natura integration. It's simply that you can use Natura's Flamestring as a substitute for a magma string.
